services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: pets-app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        working_dir: /var/www/html
        command: sh -c "./docker/php/entrypoint.sh"
        ports:
            - "9001:9000"

    nginx:
        image: nginx:alpine
        container_name: pets-nginx
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: pets-db
        environment:
            MYSQL_DATABASE: pets_app
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3307:3306"
